#ifndef H_IOB_AXI2IOB_CONF_H
#define H_IOB_AXI2IOB_CONF_H

#define IOB_AXI2IOB_ADDR_WIDTH 32
#define IOB_AXI2IOB_DATA_WIDTH 32
#define IOB_AXI2IOB_STRB_WIDTH (DATA_WIDTH / 8)
#define IOB_AXI2IOB_AXI_ID_WIDTH 8
#define IOB_AXI2IOB_VERSION 0x0081

#endif // H_IOB_AXI2IOB_CONF_H
