#ifndef H_IOB_RAM_T2P_BE_CONF_H
#define H_IOB_RAM_T2P_BE_CONF_H

#define IOB_RAM_T2P_BE_HEXFILE "none"
#define IOB_RAM_T2P_BE_ADDR_W 1
#define IOB_RAM_T2P_BE_DATA_W 1
#define IOB_RAM_T2P_BE_COL_W 8
#define IOB_RAM_T2P_BE_NUM_COL DATA_W / COL_W
#define IOB_RAM_T2P_BE_VERSION 0x0081

#endif // H_IOB_RAM_T2P_BE_CONF_H
