#ifndef H_IOB_IOB2AXIL_CONF_H
#define H_IOB_IOB2AXIL_CONF_H

#define IOB_IOB2AXIL_AXIL_ADDR_W 21
#define IOB_IOB2AXIL_AXIL_DATA_W 21
#define IOB_IOB2AXIL_ADDR_W AXIL_ADDR_W
#define IOB_IOB2AXIL_DATA_W AXIL_DATA_W
#define IOB_IOB2AXIL_VERSION 0x0081

#endif // H_IOB_IOB2AXIL_CONF_H
