#ifndef H_IOB_RAM_T2P_CONF_H
#define H_IOB_RAM_T2P_CONF_H

#define IOB_RAM_T2P_HEXFILE "none"
#define IOB_RAM_T2P_ADDR_W 1
#define IOB_RAM_T2P_DATA_W 1
#define IOB_RAM_T2P_VERSION 0x0081

#endif // H_IOB_RAM_T2P_CONF_H
