#ifndef H_IOB_UART_CSRS_CONF_H
#define H_IOB_UART_CSRS_CONF_H

#define IOB_UART_CSRS_ADDR_W 3
#define IOB_UART_CSRS_DATA_W 32
#define IOB_UART_CSRS_RST_POL 1
#define IOB_UART_CSRS_VERSION 0x0081

#endif // H_IOB_UART_CSRS_CONF_H
