#ifndef H_IOB_AXIL_MACC_CSRS_CONF_H
#define H_IOB_AXIL_MACC_CSRS_CONF_H

#define IOB_AXIL_MACC_CSRS_ADDR_W 4
#define IOB_AXIL_MACC_CSRS_DATA_W 32
#define IOB_AXIL_MACC_CSRS_VERSION 0x0081

#endif // H_IOB_AXIL_MACC_CSRS_CONF_H
